/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

<<<<<<< HEAD
=======
import MotorVehiculo.Motor;
>>>>>>> feature/AvanceGUIRadio
import SistemaRadio.SistemaRadio;
import SistemaRadio.ModoRadio;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;


 /*
 * @author Valdelomaar
 */
public class FrmInterfazRadio extends javax.swing.JFrame {
    private SistemaRadio sistemaRadio;
<<<<<<< HEAD
=======
    Motor motor = new Motor();
>>>>>>> feature/AvanceGUIRadio
    /**
     * Creates new form FrmInterfazRadio
     */
    public FrmInterfazRadio() {
        sistemaRadio = new SistemaRadio();
<<<<<<< HEAD
        initComponents();
         
=======
        

        initComponents();
    radioEncender.setEnabled(true);  // El RadioButton está habilitado
    jComboBox1.setEnabled(false);  // El ComboBox está deshabilitado por defecto
    jComboBox2.setEnabled(false);
    motor.encender();
>>>>>>> feature/AvanceGUIRadio
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
<<<<<<< HEAD
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
=======
        subirVolumen = new javax.swing.JButton();
        bajarVolumen = new javax.swing.JButton();
>>>>>>> feature/AvanceGUIRadio
        estadoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        estadoLabelRadio = new javax.swing.JLabel();
<<<<<<< HEAD
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton2.setText("-");
=======
        frecuenciaLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        radioEncender = new javax.swing.JRadioButton();
        actualizarVolumen = new javax.swing.JProgressBar();
        labelVol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subirVolumen.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        subirVolumen.setText("+");
        subirVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirVolumenActionPerformed(evt);
            }
        });

        bajarVolumen.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bajarVolumen.setText("-");
        bajarVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarVolumenActionPerformed(evt);
            }
        });
>>>>>>> feature/AvanceGUIRadio

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "FM", "Bluetooth" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

<<<<<<< HEAD
=======
        frecuenciaLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        frecuenciaLabel.setText("Frecuencia");

>>>>>>> feature/AvanceGUIRadio
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(132, 132, 132)
                .addComponent(estadoLabelRadio)
                .addContainerGap(152, Short.MAX_VALUE))
=======
                .addGap(19, 19, 19)
                .addComponent(frecuenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estadoLabelRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> feature/AvanceGUIRadio
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(72, 72, 72)
                .addComponent(estadoLabelRadio)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
=======
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(estadoLabelRadio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(frecuenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

>>>>>>> feature/AvanceGUIRadio
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        radioEncender.setText("Encender");
        radioEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEncenderActionPerformed(evt);
            }
        });

>>>>>>> feature/AvanceGUIRadio
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(estadoLabel)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
=======
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(radioEncender))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(694, 694, 694)
                        .addComponent(estadoLabel)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subirVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(bajarVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(229, 229, 229))))
>>>>>>> feature/AvanceGUIRadio
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );

=======
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(radioEncender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(subirVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bajarVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, Short.MAX_VALUE))
        );

        labelVol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVol.setText("Volumen");

>>>>>>> feature/AvanceGUIRadio
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualizarVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelVol, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualizarVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVol, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
>>>>>>> feature/AvanceGUIRadio
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_jButton1ActionPerformed


    
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedMode = (String) jComboBox1.getSelectedItem();  // Obtiene el valor seleccionado

    System.out.println("Modo seleccionado: " + selectedMode);  // Depuración
    
    // Cambiar el modo de la radio según el valor seleccionado
    switch (selectedMode) {
        case "AM":
            sistemaRadio.cambiarModo(ModoRadio.AM);  // Cambiar a AM
            break;
        case "FM":
            sistemaRadio.cambiarModo(ModoRadio.FM);  // Cambiar a FM
            break;
        case "Bluetooth":
            sistemaRadio.cambiarModo(ModoRadio.BLUETOOTH);  // Cambiar a Bluetooth
            break;
        default:
            break;      
=======
    private void subirVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirVolumenActionPerformed
           if (motor.isState() && radioEncender.isSelected()) {  // Solo si la radio está encendida
        sistemaRadio.subirVolumen();  // Subir el volumen
        actualizarVolumen();  // Actualizamos la ProgressBar
        System.out.println("Volumen: " + sistemaRadio.getVolumen());
    } else {
        mostrarMansaje("La radio debe estar encendida para ajustar el volumen.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_subirVolumenActionPerformed

public void mostrarMansaje(String texto, String titulo, int tipoMensaje) {
        JOptionPane.showMessageDialog(this, texto, titulo, tipoMensaje);
    }

    public int mostrarMensajeConfirmacion(String texto, String titulo, int tipoRespuesta, int tipoMensaje) {
        return JOptionPane.showConfirmDialog(this, texto, titulo, tipoRespuesta, tipoMensaje);
    }
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if (radioEncender.isSelected()) {  // Solo cambiar si la radio está encendida
        String selectedMode = (String) jComboBox1.getSelectedItem();  // Obtener el valor seleccionado
    
        // Limpiar el ComboBox de frecuencias
        jComboBox2.removeAllItems();
    
        // Cambiar el modo de la radio según el valor seleccionado
        switch (selectedMode) {
            case "AM":
                sistemaRadio.cambiarModo(ModoRadio.AM);
                if (motor.isState()){
                  mostrarMansaje("Modo AM Seleccionado", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                // Agregar las frecuencias AM con el prefijo al ComboBox
                jComboBox2.addItem("AM: 530 kHz");
                jComboBox2.addItem("AM: 540 kHz");
                jComboBox2.addItem("AM: 550 kHz");
                jComboBox2.addItem("AM: 560 kHz");
                jComboBox2.addItem("AM: 570 kHz");
                frecuenciaLabel.setText("Modo AM activado");
                break;
            case "FM":
                sistemaRadio.cambiarModo(ModoRadio.FM);
                if (motor.isState()){
                  mostrarMansaje("Modo FM Seleccionado", "Información", JOptionPane.INFORMATION_MESSAGE);  
                }
                
                // Agregar las frecuencias FM con el prefijo al ComboBox
                jComboBox2.addItem("FM: 88.1 MHz");
                jComboBox2.addItem("FM: 88.5 MHz");
                jComboBox2.addItem("FM: 89.0 MHz");
                jComboBox2.addItem("FM: 89.5 MHz");
                frecuenciaLabel.setText("Modo FM activado");
                break;
            case "Bluetooth":
                sistemaRadio.cambiarModo(ModoRadio.BLUETOOTH);  // Cambiar a Bluetooth
                if (motor.isState()){
                  mostrarMansaje("Modo Bluetooth Seleccionado", "Información", JOptionPane.INFORMATION_MESSAGE);  
                }
                
                // Eliminar las frecuencias ya añadidas
                jComboBox2.removeAllItems();
                frecuenciaLabel.setText("Modo Bluetooth");
                break;
            default:
                break;      
        }
    } else {
        mostrarMansaje("Primero enciende la radio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
>>>>>>> feature/AvanceGUIRadio
    }//GEN-LAST:event_jComboBox1ActionPerformed

    }
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
<<<<<<< HEAD
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    
=======
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void radioEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEncenderActionPerformed
        if (motor.isState()) {  // Si el motor está encendido
        // Activamos la radio
        sistemaRadio.cambiarModo(ModoRadio.AM); // O cualquier modo por defecto que quieras
        jComboBox1.setEnabled(true);  // Habilitar ComboBox para cambiar el modo
        jComboBox2.setEnabled(true);  // Habilitar ComboBox para seleccionar las frecuencias
        System.out.println("Radio encendida");
    } else {
        // Si el motor está apagado, desmarcar el RadioButton y mostrar un mensaje
        radioEncender.setSelected(false);
        jComboBox1.setEnabled(false);  // Deshabilitar ComboBox para cambiar el modo
        jComboBox2.setEnabled(false);  // Deshabilitar ComboBox para seleccionar las frecuencias
        mostrarMansaje("El motor está apagado. No puedes encender la radio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_radioEncenderActionPerformed

    private void bajarVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarVolumenActionPerformed
         if (motor.isState() && radioEncender.isSelected()) {  // Solo si la radio está encendida
        sistemaRadio.bajarVolumen();  // Bajar el volumen
        actualizarVolumen();  // Actualizamos la ProgressBar
        System.out.println("Volumen: " + sistemaRadio.getVolumen());
    } else {
        mostrarMansaje("La radio debe estar encendida para ajustar el volumen.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
         
    }//GEN-LAST:event_bajarVolumenActionPerformed

    private void actualizarVolumen() {
    int volumen = sistemaRadio.getVolumen();  // Obtener el volumen actual
    // Actualizamos la ProgressBar (supongamos que va de 0 a 100)
    actualizarVolumen.setValue(volumen);  // Seteamos el valor de la ProgressBar
    actualizarVolumen.setString(volumen + "%"); 
    // Opcional: mostrar el volumen como texto en la ProgressBar
    labelVol.setText("Volumen: " + volumen + "%");
}
>>>>>>> feature/AvanceGUIRadio


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInterfazRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInterfazRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInterfazRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInterfazRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInterfazRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel estadoLabelRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
=======
    private javax.swing.JProgressBar actualizarVolumen;
    private javax.swing.JButton bajarVolumen;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel estadoLabelRadio;
    private javax.swing.JLabel frecuenciaLabel;
>>>>>>> feature/AvanceGUIRadio
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
<<<<<<< HEAD
=======
    private javax.swing.JLabel labelVol;
    private javax.swing.JRadioButton radioEncender;
    private javax.swing.JButton subirVolumen;
>>>>>>> feature/AvanceGUIRadio
    // End of variables declaration//GEN-END:variables
}
