/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import AcelerarVehiculo.Acelerar;
import CombustibleVehiculo.Combustible;
import MotorVehiculo.Motor;
import SistemaClimatizacion.Climatizacion;
import SistemaKilometraje.SistemaKilometraje;
import SistemaIluminacion.Iluminacion;
import SistemaIluminacion.TipoLuz;

import javax.swing.*;
import java.awt.event.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Eduard Salas Murillo
 */
public class FrmKilometraje extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmKilometraje.class.getName());
    private Motor motor;
    private Acelerar rpm;
    private Combustible combustible;
    private SistemaKilometraje sistema;
    private Climatizacion clima;
    private Iluminacion iluminacion;
    private Timer timer;
    private double consumoTotal = 0;
    private double distanciaRecorrida = 0;

    /**
     * Creates new form FrmKilometraje
     */
    public FrmKilometraje() {
        initComponents();
        nivelConsumo.setOrientation(JProgressBar.VERTICAL);
        nivelConsumo.setMinimum(0);
        nivelConsumo.setMaximum(100);
        nivelConsumo.setValue(100);

        // Inicializar instancias de lógica
        motor = new Motor();
        rpm = new Acelerar();
        double fuelLevel = 15.6;
        combustible = new Combustible(fuelLevel);
        sistema = new SistemaKilometraje(motor, rpm);
        sistema.setCombustible(combustible);
        clima = new Climatizacion(motor);
        iluminacion = new Iluminacion(TipoLuz.DELANTERA_BAJA);

        // Encender motor al inicio
        motor.encender();

        // Valores iniciales
        kilometrosRecorridos.setText("Km: 0.0");
        consumo.setText("Consumo: 0.0 L");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kilometrosRecorridos = new javax.swing.JLabel();
        consumo = new javax.swing.JLabel();
        btnAvanzar = new javax.swing.JButton();
        nivelConsumo = new javax.swing.JProgressBar();
        btnDetener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        kilometrosRecorridos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        kilometrosRecorridos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        consumo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Encender");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        nivelConsumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDetener.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDetener.setText("Apagar");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kilometrosRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnAvanzar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetener)))
                .addGap(18, 40, Short.MAX_VALUE)
                .addComponent(nivelConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivelConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(consumo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(kilometrosRecorridos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAvanzar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDetener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        if (!motor.isState()) {
            JOptionPane.showMessageDialog(this, "¡Encienda el motor primero!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (timer != null) timer.cancel();

        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                double distancia = 0.2; // La distancia que avanzamos en cada ciclo
                int rpmFijo = 2000; // Un valor de RPM constante para el ejemplo

                if (clima.AcEncendido()) {
                    // Si el AC está encendido, el consumo aumenta.
                    // Lo manejamos con la lógica de tu clase Combustible
                    // Si tu clase Combustible no lo maneja, no hace falta.
                }
                if (iluminacion.isEstado()) {
                    // Si las luces están encendidas, el consumo aumenta.
                    // Lo manejamos con la lógica de tu clase Combustible.
                }
                
                // Aquí usamos el método fuelConsume de tu clase Combustible
                if (combustible.getFuelLevel() > 0) {
                    // CORRECCIÓN CLAVE: Llama al método fuelConsume con los dos parámetros
                    combustible.fuelConsume(distancia, rpmFijo);
                    
                    // Ya que la clase Combustible calcula el consumo,
                    // podemos obtenerlo directamente de ahí, o mantener la lógica
                    // de FrmKilometraje para los extras. Para que funcione bien,
                    // vamos a mantener el consumo total de FrmKilometraje
                    // para actualizar la etiqueta de consumo
                    double consumoParcial = 0.1;
                    if (clima.AcEncendido()) {
                        consumoParcial += 0.15;
                    }
                    if (iluminacion.isEstado()) {
                        consumoParcial += 0.10;
                    }
                    consumoTotal += consumoParcial;
                    
                    distanciaRecorrida += distancia;
                    sistema.actualizarKilometraje(distancia);

                    // CORRECCIÓN CLAVE: Usamos getFuelLevel() y getCapacityTank()
                    double nivelActual = combustible.getFuelLevel();
                    double capacidadTotal = combustible.getCapacityTank(); // La capacidad es fija en 15.6

                    int porcentaje = (int) ((nivelActual / capacidadTotal) * 100);
                    nivelConsumo.setValue(porcentaje);
                    
                    kilometrosRecorridos.setText("Km: " + String.format("%.1f", distanciaRecorrida));
                    consumo.setText("Consumo: " + String.format("%.2f", consumoTotal) + " L");
                } else {
                    nivelConsumo.setValue(0);
                    JOptionPane.showMessageDialog(null, "¡El combustible se agotó!");
                    timer.cancel();
                }
            }
        }, 0, 1000);
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        if (timer != null) timer.cancel();
        JOptionPane.showMessageDialog(this,
        "Distancia recorrida: " + String.format("%.1f", sistema.getKilometrajeTotal()) + " km\n" +
        "Consumo total: " + String.format("%.2f", consumoTotal) + " L",
        "Resumen del viaje",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmKilometraje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnDetener;
    private javax.swing.JLabel consumo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kilometrosRecorridos;
    private javax.swing.JProgressBar nivelConsumo;
    // End of variables declaration//GEN-END:variables
}
