/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MotorVehiculo.Motor;
import VehiculoPuertas.Puerta;
import VehiculoPuertas.SistemaControlPuerta;
import javax.swing.JOptionPane;
/**
 *
 * @author Valdelomaar
 */
public class FrmSistemaPuertas extends javax.swing.JFrame {
    private Puerta puerta =  new Puerta();
    private SistemaControlPuerta sistemaControlPuerta;
    Motor motor = new Motor(); 
    
    public FrmSistemaPuertas() {
        initComponents();
        sistemaControlPuerta = new SistemaControlPuerta(motor);
    }

    public void mostrarMensaje(String texto, String titulo, int tipoMensaje){
       JOptionPane.showMessageDialog(this, texto, titulo, tipoMensaje);
    }
    
    public int mostrarMensajeConfirmacion(String texto, String titulo, int tipoRespuesta, int tipoMensaje){
        return JOptionPane.showConfirmDialog(this, texto, titulo, tipoRespuesta,tipoMensaje);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puertaDela2 = new javax.swing.JButton();
        puertaTra2 = new javax.swing.JButton();
        puertaDela1 = new javax.swing.JButton();
        puertaTra1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puertaDela2.setText("PuertaDelantera2");
        puertaDela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertaDela2ActionPerformed(evt);
            }
        });

        puertaTra2.setText("PuertaTrasera2");
        puertaTra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertaTra2ActionPerformed(evt);
            }
        });

        puertaDela1.setText("PuertaDelantera1");
        puertaDela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertaDela1ActionPerformed(evt);
            }
        });

        puertaTra1.setText("PuertaTrasera1");
        puertaTra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertaTra1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/carrosin-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(puertaDela1)
                    .addComponent(puertaTra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puertaDela2)
                    .addComponent(puertaTra2))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(puertaDela2)
                        .addGap(163, 163, 163)
                        .addComponent(puertaTra2)
                        .addGap(210, 210, 210))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(puertaDela1)
                        .addGap(153, 153, 153)
                        .addComponent(puertaTra1)
                        .addGap(217, 217, 217))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puertaDela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertaDela1ActionPerformed
        try {
            if (!sistemaControlPuerta.estaPuertaAbierta("di")) {  // 
                sistemaControlPuerta.abrirPuerta("ti");
                if(motor.isState()){
                    mostrarMensaje("Puerta Delantera Izquierda Abierta","Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
                
            } else {
                sistemaControlPuerta.cerrarPuerta("ti");
                if(motor.isState()){
                    mostrarMensaje("Puerta Delantera Izquierda Cerrada","Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            System.out.println("Error al cambiar el estado de la puerta delantera izquierda: " + ex.getMessage());
}
    }//GEN-LAST:event_puertaDela1ActionPerformed

    private void puertaTra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertaTra1ActionPerformed
        try {
            if (!sistemaControlPuerta.estaPuertaAbierta("ti")) {  // 
                sistemaControlPuerta.abrirPuerta("ti");
                if(motor.isState()){
                    mostrarMensaje("Puerta Trasera Izquierda Abierta","Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
                
            } else {
                sistemaControlPuerta.cerrarPuerta("ti");
                if(motor.isState()){
                    mostrarMensaje("Puerta Trasera Izquierda Cerrada","Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
                
            }
        } catch (Exception ex) {
            mostrarMensaje("Error al cambiar el estado de la puerta trasera izquierda","Informacion",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_puertaTra1ActionPerformed

    private void puertaDela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertaDela2ActionPerformed
        try {
            if (!sistemaControlPuerta.estaPuertaAbierta("dd")) {  // 
                sistemaControlPuerta.abrirPuerta("ti");
                if(motor.isState()){
                  mostrarMensaje("Puerta delantera derecha Abierta","Informacion",JOptionPane.INFORMATION_MESSAGE);  
                }
                
            } else {
                sistemaControlPuerta.cerrarPuerta("ti");
                if(motor.isState()){
                    mostrarMensaje("Puerta Delantera Derecha Cerrada","Informacion",JOptionPane.INFORMATION_MESSAGE);
                }
               
            }
        } catch (Exception ex) {
            mostrarMensaje("Error al cambiar el estado de la puerta delantera derecha","Informacion",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_puertaDela2ActionPerformed

    private void puertaTra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertaTra2ActionPerformed
        try {
            if (!sistemaControlPuerta.estaPuertaAbierta("dd")) {  // 
                sistemaControlPuerta.abrirPuerta("ti");
                if(motor.isState()){
                   mostrarMensaje("Puerta Trasera Derecha Abierta","Informacion",JOptionPane.INFORMATION_MESSAGE); 
                }
                
            } else {
                sistemaControlPuerta.cerrarPuerta("ti");
                if(motor.isState()){
                  mostrarMensaje("Puerta trasera derecha Cerrada","Informacion",JOptionPane.INFORMATION_MESSAGE);  
                }
                
            }
        } catch (Exception ex) {
            mostrarMensaje("Error al cambiar el estado de la puerta trasera derecha","Informacion",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_puertaTra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPuertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPuertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPuertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistemaPuertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistemaPuertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton puertaDela1;
    private javax.swing.JButton puertaDela2;
    private javax.swing.JButton puertaTra1;
    private javax.swing.JButton puertaTra2;
    // End of variables declaration//GEN-END:variables
}
